#db connection(mysql)
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/jims?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dltpfks1
    mapper-locations : classpath:/mapper/**/*.xml

# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml

#logging
logging:
  level:
    com:
      group=INFO:

# JAP
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# FILE
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      max-http-form-post-size: 10MB
